# Generated by Django 3.1.7 on 2021-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('life', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
                ('study', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
    ]
