# Generated by Django 3.1.7 on 2021-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Together',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('done', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goals_together',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'managed': False},
        ),
    ]
