# Generated by Django 3.1.7 on 2021-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20210618_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('life', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
                ('study', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('done', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goals_goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Togethers',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('done', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goals_together',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.DeleteModel(
            name='Together',
        ),
    ]
