# Generated by Django 3.1.7 on 2021-06-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210618_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goal',
            table='goals_goal',
        ),
        migrations.AlterModelTable(
            name='togethers',
            table='goals_togethers',
        ),
    ]
