# Generated by Django 3.1.7 on 2021-06-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210610_2244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginuser',
            table='user',
        ),
    ]
