# Generated by Django 3.1.7 on 2021-06-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210611_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginuser',
            table='login_user',
        ),
    ]
